# Dados referente ao porquinho e cachorro

In [14]:
from sklearn.naive_bayes import MultinomialNB
import numpy as np

# [é gordinho?, tem perninha curta?, faz auau?]
porco1 = [1, 1, 0]
porco2 = [1, 1, 0]
porco3 = [1, 1, 0]
cachorro4 = [1, 1, 1]
cachorro5 = [0, 1, 1]
cachorro6 = [0, 1, 1]

dados = [porco1, porco2, porco3, cachorro4, cachorro5, cachorro6]

marcacoes = [1, 1, 1, -1, -1, -1]

misterioso1 = [1, 1, 1]
misterioso2 = [1, 0, 0]

teste = [misterioso1, misterioso2]
from sklearn.naive_bayes import MultinomialNB

modelo = MultinomialNB()
modelo.fit(dados, marcacoes)
print(modelo.predict(teste))



[-1  1]


In [22]:
dados

[[1, 1, 0], [1, 1, 0], [1, 1, 0], [1, 1, 1], [0, 1, 1], [0, 1, 1]]

In [21]:
porco1 = [1, 1, 0]
porco2 = [1, 1, 0]
porco3 = [1, 1, 0]
cachorro4 = [1, 1, 1]
cachorro5 = [0, 1, 1]
cachorro6 = [0, 1, 1]

dados = [porco1, porco2, porco3, cachorro4, cachorro5, cachorro6]

marcacoes = [1, 1, 1, -1, -1, -1]

from sklearn.naive_bayes import MultinomialNB

modelo = MultinomialNB()
modelo.fit(dados, marcacoes)

misterioso1 = [1, 1, 1]
misterioso2 = [1, 0, 0]
misterioso3 = [0, 0, 1]

teste = [misterioso1, misterioso2, misterioso3]
marcacoes_teste = [-1, 1, -1]
resultado = modelo.predict(teste)
diferencas = resultado - marcacoes_teste

acertos = [d for d in diferencas if d == 0]

total_de_acertos = len(acertos)
total_de_elementos = len(teste)

taxa_de_acerto = 100.0 * total_de_acertos / total_de_elementos

print(resultado)
print(diferencas)

modelo.fit(dados, marcacoes)         #para o modelo treinar com os nossos dados e marcações utiliza o método fit().
print(modelo.predict(teste))
diferencas = (resultado - marcacoes_teste)
print(diferencas)

print("Total de acertos do teste:",total_de_acertos,"\n", acertos)
total_de_elementos = len(teste)
print("Total de elementos da amostra: ",total_de_elementos)

taxa_de_acerto = 100.0 * total_de_acertos / total_de_elementos
print("Taxa de acerto foi: ",taxa_de_acerto)

[-1  1 -1]
[0 0 0]
[-1  1 -1]
[0 0 0]
Total de acertos do teste: 3 
 [0, 0, 0]
Total de elementos da amostra:  3
Taxa de acerto foi:  100.0


#Dados referente ao acesso de páginas do usuário no site

In [ ]:
import pandas as pd

dados = pd.read_csv('/content/drive/MyDrive/UFC /2021.1/RP/acesso.csv') 
dados.head()

In [ ]:
from sklearn.naive_bayes import MultinomialNB

x = dados[['acessou_home', 'acessou_como_funciona', 'acessou_contato']]
y = dados["comprou"]
modelo = MultinomialNB()
modelo.fit(x,y)

#print(modelo.predict([[1,0,1], [0,1,0]]))

#saber a taxa de acerto
resultado = modelo.predict(x)
diferencas = resultado - y            #y é o valor real

acertos = [d for d in diferencas if d == 0]
total_de_acertos = len(acertos)
total_de_elementos = len(x)
taxa_de_acerto = 100.0 * total_de_acertos / total_de_elementos

print("Taxa de acertos foi: ", taxa_de_acerto)
print("Total de elementos eh:", total_de_elementos)

In [ ]:
#Separar 90% para treino e 10% para teste
from sklearn.naive_bayes import MultinomialNB

x = dados[['acessou_home', 'acessou_como_funciona', 'acessou_contato']]
y = dados["comprou"]

treino_dados = x[:90]
treino_marcacoes = y[:90]

teste_dados = x[-9:]            #as ultimas 9 linhas
teste_marcacoes = y[-9:]




In [ ]:
modelo = MultinomialNB()
modelo.fit(treino_dados, treino_marcacoes)

resultado = modelo.predict(teste_dados)
diferencas = resultado - teste_marcacoes  

acertos = [d for d in diferencas if d == 0]
total_de_acertos = len(acertos)
total_de_elementos = len(teste_dados)
taxa_de_acerto = 100.0 * total_de_acertos / total_de_elementos

print("Taxa de acertos foi: ", taxa_de_acerto)
print("Total de elementos eh:", total_de_elementos)

# Classificação de variaveis categóricas

In [ ]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Machine Learning/cursos.csv') 
df.head()

home       busca  logado  comprou
0     0  algoritmos       1        1
1     0        java       0        1
2     1  algoritmos       0        1
3     1        ruby       1        0
4     1        ruby       0        1

In [ ]:

X_df = df[['home', 'busca', 'logado']]
Y_df = df['comprou']

#transformamos uma variável categórica em diversas categorias de acordo com a quantidade de dados distintos,
#esses valores são conhecidos como dummies, pois eles representam a mesma variável, porém com valores binários.
Xdummies_df = pd.get_dummies(X_df).astype(int)
Ydummies_df = Y_df

#transformando os valores dos data frames em arrays
X = Xdummies_df.values
Y = Ydummies_df.values

porcentagem_treino = 0.9

tamanho_de_treino = int(porcentagem_treino * len(Y))
tamanho_de_teste = len(Y) - tamanho_de_treino

treino_dados = X[:tamanho_de_treino]
treino_marcacoes = Y[:tamanho_de_treino]

teste_dados = X[-tamanho_de_teste:]
teste_marcacoes = Y[-tamanho_de_teste:]

Testando o modelo

In [ ]:
from sklearn.naive_bayes import MultinomialNB
modelo = MultinomialNB()
modelo.fit(treino_dados, treino_marcacoes)

resultado = modelo.predict(teste_dados)

diferencas = resultado - teste_marcacoes

acertos = [d for d in diferencas if d == 0]
total_de_acertos = len(acertos)
total_de_elementos = len(teste_dados)

taxa_de_acerto = 100.0 * total_de_acertos / total_de_elementos

print(taxa_de_acerto)
print(total_de_elementos)

82.0
100


In [ ]:
print(sum(Y))
len(Y)

832


1000

Calculando a taxa de acertos e a taxa de acertos base 

In [ ]:
#a  eficacia do algoritmo que chuta tudo 0 ou 1 
acerto_de_um = len(Y[Y==0])
acerto_de_zero = len(Y[Y==1])
taxa_de_acerto_base = 100.0 * max(acerto_de_um, acerto_de_zero) / len(Y)

taxa_de_acerto = 100.0 * total_de_acertos / total_de_elementos

print("taxa de acertos: ",taxa_de_acerto)

print("taxa de acerto base: ", taxa_de_acerto_base)

taxa de acertos:  82.0
taxa de acerto base:  0.0


Calculando a quantidade de zeros e uns

In [ ]:
acerto_de_um = len(Y[Y==0])
acerto_de_zero = len(Y[Y==1])
#X[Y==0] #quem nao comprou 

## Mudando o resultado de binario para true e false

In [ ]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/alura-cursos/machine-learning-introducao-a-classificacao/master/busca.csv') 
df.head()

home       busca  logado comprou
0     0  algoritmos       1     sim
1     0        java       0     sim
2     1  algoritmos       0     sim
3     1        ruby       1     nao
4     1        ruby       0     sim

In [ ]:
from collections import Counter
from sklearn.naive_bayes import MultinomialNB

X_df = df[['home', 'busca', 'logado']]
Y_df = df['comprou']

#transformamos uma variável categórica em diversas categorias de acordo com a quantidade de dados distintos,
#esses valores são conhecidos como dummies, pois eles representam a mesma variável, porém com valores binários.
Xdummies_df = pd.get_dummies(X_df).astype(int)
Ydummies_df = Y_df

#transformando os valores dos data frames em arrays
X = Xdummies_df.values
Y = Ydummies_df.values

porcentagem_treino = 0.9

tamanho_de_treino = int(porcentagem_treino * len(Y))
tamanho_de_teste = len(Y) - tamanho_de_treino

treino_dados = X[:tamanho_de_treino]
treino_marcacoes = Y[:tamanho_de_treino]

teste_dados = X[-tamanho_de_teste:]
teste_marcacoes = Y[-tamanho_de_teste:]

#testando o modelo
modelo = MultinomialNB()
modelo.fit(treino_dados, treino_marcacoes)

resultado = modelo.predict(teste_dados)
acertos = (resultado == teste_marcacoes)  

total_de_acertos = sum(acertos)
total_de_elementos = len(teste_dados)
print("Total de elementos: ",total_de_elementos)


acerto_base = max(Counter(Y).values())
taxa_de_acerto_base = 100.0 * acerto_base / len(Y)
taxa_de_acerto = 100.0 * total_de_acertos / total_de_elementos

print("taxa de acertos: ",taxa_de_acerto)
print("taxa de acerto base: ", taxa_de_acerto_base)

Total de elementos:  100
taxa de acertos:  82.0
taxa de acerto base:  83.2


# Naive Bayes e maxium a posteriori por trás dos panos